#!/usr/bin/env bash

# Simple local build helper for Emacs VTerm formula.
#
# Examples:
#   ./build --with-xwidgets
#   ./build --HEAD

set -e

SOURCE_FILE=Formula/emacs-vterm.rb
SOURCE_NAME=EmacsVterm

TARGET_FILE=Formula/emacs-vterm-local.rb
TARGET_NAME=EmacsVtermLocal

function cleanup {
  rm -f "$TARGET_FILE"
}

trap cleanup INT TERM EXIT

cp "$SOURCE_FILE" "$TARGET_FILE"
sed -i -e "s/class $SOURCE_NAME/class $TARGET_NAME/g" "$TARGET_FILE"

export HOMEBREW_EMACS_VTERM_MODE=local
export HOMEBREW_NO_INSTALL_UPGRADE=true
export HOMEBREW_NO_AUTO_UPDATE=true
export HOMEBREW_DEVELOPER=1

# shellcheck disable=SC2068
HOMEBREW_DEVELOPER=1 brew install --formula ./$TARGET_FILE $@
